name: Build Flet Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.7'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          libssl-dev \
          libffi-dev \
          python3-dev \
          unzip \
          wget \
          curl \
          git

    - name: Install Flutter
      run: |
        wget https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.19.6-stable.tar.xz
        tar xf flutter_linux_3.19.6-stable.tar.xz
        echo "$GITHUB_WORKSPACE/flutter/bin" >> $GITHUB_PATH
        echo "$GITHUB_WORKSPACE/flutter/.pub-cache/bin" >> $GITHUB_PATH
    
    - name: Flutter doctor and configure Android SDK
      run: |
        flutter channel stable
        flutter upgrade
        flutter doctor -v
        yes | flutter doctor --android-licenses
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flet==0.25.1
        pip install pandas==2.2.2
        pip install numpy==2.1.1
        pip install pyinstaller
    
    - name: Install Flet CLI and packaging dependencies
      run: |
        pip install flet-core
        pip install setuptools
    
    - name: Check versions
      run: |
        python --version
        flutter --version
        dart --version
    
    - name: Build Android APK
      run: |
        # Ensure you're in the correct directory with your main.py
        # Replace 'main.py' with your actual main application file
        flet build apk
    
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: dist/*.apk
        retention-days: 5

# Optional: Uncomment and modify if you want to create a release
#   create-release:
#     needs: build-android
#     runs-on: ubuntu-latest
#     steps:
#     - name: Download APK
#       uses: actions/download-artifact@v4
#       with:
#         name: android-apk
    
#     - name: Create GitHub Release
#       uses: softprops/action-gh-release@v2
#       if: startsWith(github.ref, 'refs/tags/')
#       with:
#         files: '*.apk'
